version: "3"
services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: >
      sh -c "npm run build && npm start"

  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      - PORT=5000
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app  # Corrigindo o caminho do volume
    command: >
      sh -c "npm run dev"
    depends_on:
      - frontend
